version: '3'
services:
  nginx:
    build: ./nginx/
    container_name: nginx-container
    ports:
      - 8888:80
    links:
      - php
    networks:
      - youcannet  
    volumes:
      - ./php/:/var/www/html/    
  php:
    container_name: php-app
    image: php:7.0-fpm
    expose:
      - 9000
    networks:
      - youcannet  
    volumes:
      - ./php:/var/www/html
  haproxy:
    image: haproxy
    networks:
      - youcannet
    links:
      - nginx  
    volumes:
      - ./haproxy/:/usr/local/etc/haproxy  
    ports:
      - "80:80"     
networks:
  youcannet:
    driver: bridge
